[tool.setuptools]
name = "nvtx-mock"
version = "0.1.0"
author = "Yinying Yao"
author_email = "yaoyy.hi@gmail.com"
description = "A mock package for NVTX C headers"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"