name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
        tree | echo 'Never mind'
        ls $(dirname $(which python))/../include

    - name: Build and upload package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        tree | echo 'Never mind'
        python setup.py sdist bdist_wheel
        ls $(dirname $(which python))/../include
        python -m twine upload dist/*