name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: 
          - "3.11"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Conda on 
      uses: conda-incubator/setup-miniconda@v3
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
        tree | ls -a
        ls $(dirname $(which python))/../include

    - name: Build and upload package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        tree | ls -a
        python setup.py sdist bdist_wheel
        ls $(dirname $(which python))/../include
        python -m twine upload dist/*