name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
        tree | echo 'Never mind'
        ls $(dirname $(which python))/../include
        git submodule init
        git submodule update

    - name: Build and upload package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        tree | echo 'Never mind'
        # Build only source distribution (no need for wheels)
        python setup.py sdist
        
        # Optional: List include directories if you need to debug/include headers
        ls $(dirname $(which python))/../include
        
        # Upload only the source distribution (.tar.gz)
        python -m twine upload dist/*.tar.gz